/**
 * Stage-4 fold: usage buckets fold from a recorded plain jsonl log, the
 * closed form stays byte-identical in value with the python oracle (pinned
 * values generated by `artifacts/turn_cost.py`), and bad inputs refuse loud.
 * The spec writes fixture logs under its own mkdtemp and removes it after.
 */

import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { closedFormTaskCost, DO_MODEL_RATES, foldSessionUsage, foldSessionUsageByModel, priceFoldMicros, priceModelsMicros } from './wind-up-cost-fold.ts'

let root: string

beforeAll(async () => {
  root = await mkdtemp(join(tmpdir(), 'dsh-wind-up-fold-'))
})

afterAll(async () => {
  await rm(root, { recursive: true, force: true })
})

async function writeLog(name: string, lines: unknown[]): Promise<string> {
  const path = join(root, name)
  await writeFile(path, lines.map(line => `${JSON.stringify(line)}\n`).join(''))
  return path
}

const HEADER = { type: 'session', version: 3, id: 'recorded', createdAt: 1, delegationDepth: 0, isSeeded: false }

const assistantWithUsage = (usage: Record<string, number>, model?: string) => ({
  type: 'assistant/message',
  seq: 2,
  time: 2,
  data: {
    turn: 1, step: 1,
    message: { role: 'assistant', content: [], ...model === undefined ? {} : { source: { provider: 'digitalocean', model } } },
    stream: [], usage,
  },
})

describe('foldSessionUsage', () => {
  it('attributes usage to each logged model and prices under the DO table', async () => {
    const path = await writeLog('mixed.jsonl', [
      HEADER,
      assistantWithUsage({ inputTokens: 1_000_000, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0 }, 'qwen3.8-max'),
      assistantWithUsage({ inputTokens: 1_000_000, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0 }, 'deepseek-v4-flash-0731'),
      assistantWithUsage({ inputTokens: 500_000, outputTokens: 0 }),
    ])
    const fold = foldSessionUsageByModel(path)
    expect(fold.byModel['qwen3.8-max']?.uncachedInputTokens).toBe(1_000_000)
    expect(fold.byModel['deepseek-v4-flash-0731']?.uncachedInputTokens).toBe(1_000_000)
    expect(fold.byModel['']?.uncachedInputTokens).toBe(500_000)
    // qwen 2.00/M + flash-0731 0.14/M = $2.14; the unattributed half needs a fallback.
    const micros = priceModelsMicros(
      fold.byModel,
      DO_MODEL_RATES,
      { inputPerMillionUsd: 1, outputPerMillionUsd: 1, cacheReadPerMillionUsd: 0, cacheWritePerMillionUsd: 0 },
    )
    expect(micros).toBe(2_140_000 + 500_000)
    const known = { ...fold.byModel }
    delete known['']
    expect(priceModelsMicros(known, DO_MODEL_RATES)).toBe(2_140_000)
    const missing = { 'mystery-model': fold.byModel['']! }
    expect(() => priceModelsMicros(missing, DO_MODEL_RATES)).toThrow(/mystery-model/)
  })

  it('folds the four buckets plus turns and steps across scopes', async () => {
    const path = await writeLog('parent.jsonl', [
      HEADER,
      { type: 'turn/start', data: { turn: 1 } },
      { type: 'step/start', data: { turn: 1, step: 1 } },
      assistantWithUsage({ inputTokens: 1000, outputTokens: 200, cacheReadTokens: 5000, cacheWriteTokens: 100 }),
      assistantWithUsage({ inputTokens: 50, outputTokens: 5 }),
      { type: 'step/end', data: { turn: 1, step: 1 } },
      // Malformed usage rows are skipped, not fatal: providers lie.
      assistantWithUsage({ inputTokens: -1, outputTokens: 4 }),
      { type: 'assistant/message', data: { turn: 1, step: 1, message: {} } },
      { type: 'turn/end', data: { turn: 1, reason: { kind: 'completed' } } },
    ])
    const fold = foldSessionUsage(path)
    expect(fold.id).toBe('recorded')
    expect(fold.turns).toBe(1)
    expect(fold.steps).toBe(1)
    expect(fold.uncachedInputTokens).toBe(1050)
    expect(fold.outputTokens).toBe(205)
    expect(fold.cacheReadTokens).toBe(5000)
    expect(fold.cacheWriteTokens).toBe(100)
  })

  it('refuses a zstd-compressed log', async () => {
    const path = join(root, 'compressed.jsonl.zstd')
    await writeFile(path, Buffer.concat([Buffer.from([0x28, 0xb5, 0x2f, 0xfd]), Buffer.from('blob')]))
    expect(() => foldSessionUsage(path)).toThrow(/zstd/)
  })

  it('refuses logs without a session header and lines that are not JSON', async () => {
    const noHeader = await writeLog('noheader.jsonl', [{ type: 'turn/start' }])
    expect(() => foldSessionUsage(noHeader)).toThrow(/header/)
    const garbage = join(root, 'garbage.jsonl')
    await writeFile(garbage, `${JSON.stringify(HEADER)}\nnot json\n`)
    expect(() => foldSessionUsage(garbage)).toThrow(/line 2/)
  })
})

describe('closedFormTaskCost oracle parity', () => {
  // Pinned values generated by artifacts/turn_cost.py::task_cost so the
  // offline report and the oracle share one arithmetic; regenerating the
  // oracle's numbers by hand is exactly the drift this pins.
  type CostArgs = [number, number, number, number, number, number, number, number, number, number]
  it.each([
    { args: [100000, 20000, 100000, 20000, 6, 3, 2.0, 6.0, 0.1, 300] as CostArgs, usd: 1.3716 },
    { args: [0, 20000, 0, 20000, 6, 0, 2.0, 6.0, 0.1, 300] as CostArgs, usd: 0.2236 },
    { args: [50000, 10000, 40000, 8000, 4, 2, 0.27, 1.1, 0.0, 0] as CostArgs, usd: 0.08196 },
  ])('matches the oracle to the fourth decimal for %o', ({ args, usd }) => {
    expect(closedFormTaskCost(...args)).toBeCloseTo(usd, 4)
  })
})

describe('priceFoldMicros', () => {
  it('prices folded buckets under deployment rates in micros', async () => {
    const path = await writeLog('priced.jsonl', [
      HEADER,
      assistantWithUsage({ inputTokens: 1_000_000, outputTokens: 500_000, cacheReadTokens: 2_000_000, cacheWriteTokens: 250_000 }),
    ])
    const fold = foldSessionUsage(path)
    expect(priceFoldMicros(fold, {
      inputPerMillionUsd: 0.5,
      outputPerMillionUsd: 2,
      cacheReadPerMillionUsd: 0.1,
      cacheWritePerMillionUsd: 0.6,
    })).toBe(1_850_000)
  })
})
